site_name: Omicron Documentation
nav:
    - Home: 'index.md'
    - Getting started: 'getting-started.md'
    - Style:
        - 'Alert': 'style/alert.md'
        - 'Button': 'style/button.md'
        - 'Grid': 'style/grid.md'
    - 'JavaScript':
        - 'Tabs': 'javascript/tabs.md'
        - 'Modal': 'javascript/modal.md'
theme:
    name: readthedocs
    highlightjs: true